### PR TITLE
Adding f string

### PR DESCRIPTION
**Pull request by Bernardoow**
This is a task of issue #314.

### CODE REVIEW

**Comment by Bernardoow** [comment]
I will fix every thing until tomorrow.

The tests don't get this error =>

In the file dynaconf/contrib/django_dynaconf/dynaconf_django_conf.py:
Line 20:46: E999 SyntaxError: invalid syntax

**Comment by Bernardoow** [comment]
How re run the pep8speaks?

**Comment by rochacbruno** [comment]
@Bernardoow I dont know, it is supposed to update based on each new commit.

**Comment by Bernardoow** [comment]
I fix the pep8speaks reports. I check the doc of it and found

> The bot makes a single comment on the Pull Request and keeps updating it on new commits. No hustle on emails

I created one repo to test this and I don't know why it don't updated the msg.

**Comment by rochacbruno** [comment]
@Bernardoow CI is failing and looks like it it because your pre-commit is not running I guess.

Can you run `make run-pre-commit` and then commit/push again?

**Comment by Bernardoow** [comment]
On Last commit =>

```bash
➜  dynaconf git:(adding_f_string) ✗ git commit -m "Fixing flaked reports-v2."
Reorder python imports...................................................Passed
black....................................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Debug Statements (Python)................................................Passed
Fix python encoding pragma...............................................Passed
flake8...................................................................Passed
[adding_f_string 6274f3c] Fixing flaked reports-v2.
 4 files changed, 29 insertions(+), 16 deletions(-)
```

make run-pre-commit =>

``` bash
make run-pre-commit
rm -rf .tox/
pre-commit run --files $(find -regex '.*\.\(py\|yaml\|yml\|md\)') -v
Reorder python imports...................................................Passed
- hook id: reorder-python-imports
- duration: 0.42s
black....................................................................Failed
- hook id: black
- duration: 0.73s
- files were modified by this hook

reformatted /home/bernardo/projetos/dynaconf/dynaconf/contrib/flask_dynaconf.py
reformatted /home/bernardo/projetos/dynaconf/dynaconf/loaders/env_loader.py
reformatted /home/bernardo/projetos/dynaconf/dynaconf/loaders/base.py
reformatted /home/bernardo/projetos/dynaconf/dynaconf/default_settings.py
reformatted /home/bernardo/projetos/dynaconf/dynaconf/loaders/__init__.py
reformatted /home/bernardo/projetos/dynaconf/dynaconf/loaders/redis_loader.py
reformatted /home/bernardo/projetos/dynaconf/dynaconf/loaders/py_loader.py
reformatted /home/bernardo/projetos/dynaconf/example/app/app.py
reformatted /home/bernardo/projetos/dynaconf/dynaconf/utils/files.py
reformatted /home/bernardo/projetos/dynaconf/example/app_with_dotenv/app.py
reformatted /home/bernardo/projetos/dynaconf/example/full_example.py
reformatted /home/bernardo/projetos/dynaconf/example/multiple_folders/app.py
reformatted /home/bernardo/projetos/dynaconf/example/multiple_sources/app.py
reformatted /home/bernardo/projetos/dynaconf/dynaconf/cli.py
reformatted /home/bernardo/projetos/dynaconf/example/toml_with_secrets/program.py
reformatted /home/bernardo/projetos/dynaconf/example/yaml_example/yaml_as_extra_config/app.py
reformatted /home/bernardo/projetos/dynaconf/example/toml_example/app.py
reformatted /home/bernardo/projetos/dynaconf/example/validators/with_python/app.py
reformatted /home/bernardo/projetos/dynaconf/example/yaml_example/settings_file/app.py
All done! ✨ 🍰 ✨
19 files reformatted, 167 files left unchanged.

Trim Trailing Whitespace.................................................Passed
- hook id: trailing-whitespace
- duration: 0.12s
Fix End of Files.........................................................Passed
- hook id: end-of-file-fixer
- duration: 0.12s
Check Yaml...............................................................Passed
- hook id: check-yaml
- duration: 0.13s
Check for merge conflicts................................................Passed
- hook id: check-merge-conflict
- duration: 0.04s
Debug Statements (Python)................................................Passed
- hook id: debug-statements
- duration: 0.07s
Fix python encoding pragma...............................................Passed
- hook id: fix-encoding-pragma
- duration: 0.05s
flake8...................................................................Passed
- hook id: flake8
- duration: 0.64s


```


**I think one diference was executed black formatter lib.**

**Comment by Bernardoow** [comment]
It is ok? Should I do any change?

**Comment by rochacbruno** [comment]
@Bernardoow Ci is failing

```

    
        settings_file = tmpdir.join("settings.toml")
        settings_file.write(MIXED.format(ext))
    
        toml_plugin_file = tmpdir.join("plugin1.toml")
        toml_plugin_file.write(TOML_PLUGIN)
    
        json_plugin_file = tmpdir.join(f"plugin2.{ext}")
        json_plugin_file.write(PLUGIN_TEXT[ext])
    
        settings = LazySettings(
            ENV_FOR_DYNACONF="DEFAULT",
            silent=False,
            LOADERS_FOR_DYNACONF=False,
            ROOT_PATH_FOR_DYNACONF=str(tmpdir),
            SETTINGS_FILE_FOR_DYNACONF=str(settings_file),
        )
    
        assert settings.DEBUG is False
>       assert settings.DATABASE_URI == "f{ext}.example.com"
E       AssertionError: assert 'ini.example.com' == 'f{ext}.example.com'
E         - f{ext}.example.com
E         + ini.example.com

ext        = 'ini'
json_plugin_file = local('/tmp/pytest-of-vsts/pytest-0/test_load_nested_different_typ3/plugin2.ini')
settings   = <dynaconf.base.LazySettings object at 0x7fd3a5e82748>
settings_file = local('/tmp/pytest-of-vsts/pytest-0/test_load_nested_different_typ3/settings.toml')
tmpdir     = local('/tmp/pytest-of-vsts/pytest-0/test_load_nested_different_typ3')
toml_plugin_file = local('/tmp/pytest-of-vsts/pytest-0/test_load_nested_different_typ3/plugin1.toml')

```

**Comment by Bernardoow** [comment]
@rochacbruno sorry for that. Fixed the bug =/.

Notice.. I didn't remove every format because I must be change some logic.

`/home/bernardo/projetos/dynaconf/dynaconf/validator.py:
  159              if self.must_exist is True and not exists:
  160                  raise ValidationError(
  161:                     self.messages["must_exist_true"].format(name=name, env=env)
  162                  )
  163              elif self.must_exist is False and exists:
  164                  raise ValidationError(
  165:                     self.messages["must_exist_false"].format(
  166                          name=name, env=env
  167                      )
  ...
  178                  if not self.condition(value):
  179                      raise ValidationError(
  180:                         self.messages["condition"].format(
  181                              name=name,
  182                              function=self.condition.__name__,
  ...
  191                  if not op_function(value, op_value):
  192                      raise ValidationError(
  193:                         self.messages["operations"].format(
  194                              name=name,
  195                              operation=op_function.__name__,

/home/bernardo/projetos/dynaconf/dynaconf/loaders/__init__.py:
  150              dirname = os.path.dirname(mod_file)
  151              filename, extension = os.path.splitext(os.path.basename(mod_file))
  152:             new_filename = tmpl.format(env.lower(), filename, extension)
  153              env_mod_file = os.path.join(dirname, new_filename)
  154:             global_filename = tmpl.format("global", filename, extension)
  155              global_mod_file = os.path.join(dirname, global_filename)
  156          else:

/home/bernardo/projetos/dynaconf/tests/test_nested_loading.py:
  229  
  230      settings_file = tmpdir.join("settings.toml")
  231:     settings_file.write(MIXED.format(ext))
  232  
  233      toml_plugin_file = tmpdir.join("plugin1.toml")

/home/bernardo/projetos/dynaconf/tests/test_validators.py:
  246          settings.validators.validate()
  247  
  248:     assert custom_msg.format(
  249          name="VERSION", value="1", env="DEVELOPMENT"
  250      ) in str(error)
  ...
  281          ).validate(settings)
  282  
  283:     assert custom_msg.format(
  284          name="VERSION", value="1", env="DEVELOPMENT"
  285      ) in str(error_custom_message)

9 matches across 4 files`

**Pull request merged**
