### PR TITLE
Refactor Vault integration

### PR DESCRIPTION
**Pull request by VaultVulp**
Initial motivation for this PR was to introduce another authorization strategy for Vault: [AppRole](https://www.vaultproject.io/docs/auth/approle.html#approle-auth-method).

After the first step of refactoring I've found some minor inconsistencies in the source code and documentation:
* I've updated default value for VAULT_PATH_FOR_DYNACONF. 

	Default value for VAULT_PATH_FOR_DYNACONF ("/secret/data/") led to "/v1/secret/data/secret/data/" path in Vault. But documentation stated that secrets will be read from "/secret/dynaconf". [HVAC initializer](https://github.com/hvac/hvac/blob/develop/hvac/api/secrets_engines/kv_v2.py#L82), [vault_loader.load](https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/loaders/vault_loader.py#L69)

* I've added all meaningful VAULT_*_FOR_DYNACONF configuration parameters to `docs/guides/configuration.md`. Sadly this led to a huge diff in the `configuration.md`.

* I propose a removal of `VAULT_SESSION_FOR_DYNACONF` parameter due to the fact that this parameter is very hard to setup properly via default instruments (.toml, .env, etc), but it still can be accessed with the `VAULT_FOR_DYNACONF` parameter at a run time.

I've tried (and failed :) ) to minimize the impact of this PR, but I may try to split this PR into multiple, if this is required.

If you have any suggestions, comments, questions - feel free to contact me.

P.S. Thanks for this awesome project - looking forward to use it more effectively in my projects.

### CODE REVIEW

**Comment by rochacbruno** [comment]
@psav @rsnyman can you help me reviewing this PR? I am asking because you were the latest who changed this area.

**Comment by rochacbruno** [comment]
Hey @VaultVulp I'll wait for some input on this and will try to test myself by the weekend.

Thanks.

**Comment by VaultVulp** [comment]
@rochacbruno thank you! Looking forward to any feedback.

**Comment by rsnyman** [comment]
Hi @rochacbruno @VaultVulp 

Sorry, I've been away, I'll take a look in the next few days.

**Pull request merged**
