### PR TITLE
Just preparing tests for multiple python versions

### PR DESCRIPTION
**Pull request by ellisonleao**
Also:
- fix docs path on gitignore
- adding tox on test.req

### CODE REVIEW

**Comment by rochacbruno** [comment]
:+1:

**Comment by rochacbruno** [comment]
six is already on project, so it can be used to replace invalid code ex: #8

**Comment by ellisonleao** [comment]
Looks like travis doesn't support 3.5 for now https://github.com/travis-ci/travis-ci/issues/4794

**Comment by rochacbruno** [comment]
Python3.5 is available from the deadsnakes repo. Add the following to your .travis.yml:

```
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
```

**Comment by ellisonleao** [comment]
what about using https://github.com/ryanhiebert/tox-travis ?

**Comment by ellisonleao** [comment]
hey @rochacbruno any thoughts on this?

**Comment by rochacbruno** [comment]
@ellisonleao your call! you decide! I dont have too much experience with tox.

**Comment by ellisonleao** [comment]
the problem for me here is production vs dev . Tox makes it easier to test on multiple python versions locally. Travis can test on multiple versions, but we need to keep committing and checking the builds. there are some projects to simulate the builds locally (https://github.com/travis-ci/travis-build) but i found it very overengineering for what we need.

Do we need to support python 3.5 now?

**Comment by rochacbruno** [comment]
we can move to WerckerCI

http://devcenter.wercker.com/docs/languages/python.html

which uses images to test https://hub.docker.com/_/python/

(maybe travis can use docker images?)

**Comment by ellisonleao** [comment]
Looks like they can, not sure about the complexity

https://docs.travis-ci.com/user/docker/

**Pull request closed without merging**
