### PR TITLE
Add support to export merged env to filesystem via cli.

### LINKED ISSUE #200: Export merged environment to yaml
I'm looking for a way to "flatten" the settings into a single `values.yaml` file from the following `settings.yaml`.  

Assume that `ENV_FOR_DYNACONF=development`

```
global:
  a: 1
 
default:
  b: 2

development: 
  foo:
    bar:
      c: 3

production: 
  foo:
    bar:
      c: 4
```

Desired `values.yaml`:
```
a: 1
b: 2
foo:
  bar:
    c: 3
```

Using `print(yaml.dump(settings.as_dict()))` works for the top-level keys but the nested keys returned as *DynaBox* types.

### PR DESCRIPTION
**Pull request by rochacbruno**
fix #200

```bash
dynaconf list -o path/to/file.yaml --output-flat
```

### CODE REVIEW

**Comment by rochacbruno** [comment]
Hi @austinnichols101 can I get a review

**Comment by austinnichols101** [comment]
@rochacbruno sorry for the delay - been dealing with hurricane prep.

**Comment by rochacbruno** [comment]
@austinnichols101 thanks for feedback, and I hope you are safe from the hurricane.

**Comment by rochacbruno** [comment]
@austinnichols101 I'll merge this one, and then open a new issue with your idea to turn _store to a DynaBox as moving to a case-less first level may be a breaking change.

**Pull request merged**
