### PR TITLE
Fix  base loader when having no ENVVAR_PREFIX_ (Addresses #177)

### LINKED ISSUE #177: Correct usage of ENVVAR_PREFIX_ vs. ENV_
I think some clarification is required on the different use-cases of the new ENVVAR_PREFIX vs.  using ENV. There are multiple occurrences throughout dynaconf that are very confusing and use ENVVAR_PREFIX where I would have expected ENV to be used, for example:

* https://github.com/rochacbruno/dynaconf/blob/1bb2c39ae6a39cbbd32ca8ef39ef7ea5732a9418/dynaconf/base.py#L842
* https://github.com/rochacbruno/dynaconf/blob/1bb2c39ae6a39cbbd32ca8ef39ef7ea5732a9418/dynaconf/contrib/flask_dynaconf.py#L50
* https://github.com/rochacbruno/dynaconf/blob/e48521790a72fa4756a9d0eb8d715da562642f25/dynaconf/cli.py#L468-L469
* https://github.com/rochacbruno/dynaconf/blob/3ba4ed1f0a929289a111157e1d6c06b2d072925a/dynaconf/loaders/base.py#L125

These all seem to expect a value that is actually the "working environment" (we discussed the difference in #166), yet they *use* the environment variable prefix.

### PR DESCRIPTION
**Pull request by janw**
Fix #177

### CODE REVIEW

**Comment by rochacbruno** [comment]
I merged master to make it mergeable.

**Comment by janw** [comment]
@rochacbruno Oops, sorry. I thought I rebased beforehand 🙈

**Comment by janw** [comment]
@rochacbruno Any plans on when to release 2.0.2? Would love to update our dependencies for this particular issue.

**Comment by rochacbruno** [comment]
@janw https://github.com/rochacbruno/dynaconf/releases/tag/2.0.2

**Pull request merged**
