### PR TITLE
Fix #127 add configurable yaml loader method, default to full_load

### LINKED ISSUE #127: YAML.load without a loader is deprecated for security purposes
We've started seeing the following warning:
```
lib/python3.6/site-packages/dynaconf/loaders/base.py:95: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```

See here: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

### PR DESCRIPTION
**Pull request by rochacbruno**
Fix #127 
See: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

### CODE REVIEW

**Comment by dmsimard** [comment]
I'm not sure what is the delta between the latest release on PyPi and master with this branch but I tested this and I'm not quite getting the result I expected.

With the latest dynaconf from pypi, I get the YAMLLoadWarning:
```
lib/python3.6/site-packages/dynaconf/loaders/base.py:95: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  'ENCODING_FOR_DYNACONF', 'utf-8'
```

When I install this branch instead, there's no warning at all, even with ``export YAML_LOADER_FOR_DYNACONF=unsafe_load``

Am I missing something obvious ?

**Comment by rochacbruno** [comment]
@dmsimard You are right, I forgot to add the warning, updated now!

**Comment by dmsimard** [comment]
@rochacbruno I didn't realize we had to create a new warning. I tried your last patch and it works for me. Thanks :+1:

**Comment by dmsimard** [comment]
@rochacbruno I realize 1.2.1 was released recently -- is there going to be a 1.2.2 with this patch soon ?

**Comment by rochacbruno** [comment]
I want to include more fixes in next release, django fixes. Maybe friday.

I can release earlier if you need it.

**Comment by dmsimard** [comment]
@rochacbruno sorry, had missed your comment. The fix would be nice to have in a release so it's less noisy :+1:

**Pull request merged**
